### ISSUE TITLE
OS X linking issues

### ISSUE THREAD

**Issue by reaperhulk** [technion/libscrypt#30]
The Makefile specifies an `install-osx` target that renames `libscrypt.so.0` to `libscrypt.0.dylib`. Unfortunately this rename actually causes the library to be unusable as the internal name of the library is still `libscrypt.so.0`:

```
$ otool -L libscrypt.0.dylib
libscrypt.so.0:
    libscrypt.so.0 (compatibility version 0.0.0, current version 0.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```

I am not particularly skilled with Makefiles so I'm unsure what the correct fix is here. If you manually change the Makefile to use `libscrypt.0.dylib` as its native name then everything works as expected, but that is not a real fix.

**Comment by y** [comment]
Still doesn't link on OSX:

    ld: unknown option: -z
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
