### ISSUE TITLE
benchmarks and sse2 optimized version

### ISSUE THREAD

**Issue by y** [technion/libscrypt#37]
Could you provide a benchmark of libscrypt vs. the reference implementation, like that of scrypt-jane: https://github.com/floodyberry/scrypt-jane

Could you also also consider adding an sse2 optimized version like the reference version has.

**Comment by technion** [comment]
Hi,

This library serves as a wrapper around the reference functions and doesn't contain my own implementation of the hash function. There's no value benchmarking the code that creates a salt, and formats the resulting hash for you. scrypt-jane is only a hashing function implementation. It makes sense for them to create such a benchmark.

sse2 presents some issues.  Specifically, usefully using it requires either an autoconf harness, or an issue prone build process. Package builders will always build for the lowest common denominator, and leave these out anyway. I won't be going down this path.
