### ISSUE TITLE
Export SHA256

### ISSUE THREAD

**Issue by chfast** [technion/libscrypt#47]
Can I export sha256 function from this library?

**Comment by chfast** [comment]
@technion ?

**Comment by technion** [comment]
This was originally deliberately avoided in order to avoid clashes with other crypto libraries. However, I was subsequently provided a PR to rename the SHA256 functions to avoid the clash.

If you want to export these functions now, I'd be happy to take a PR.

**Comment by chfast** [comment]
Ok, I will do it.
