### ISSUE TITLE
The libscrypt_scrypt function takes 8 to 13 seconds to run.

### ISSUE THREAD

**Issue by yinchonging** [technion/libscrypt#50]
On iPhone X.
Is that right ? please!

`
{n: 262144, r: 8, p: 1, dklen: 32}
`

**Comment by technion** [comment]
Unfortunately with high work orders, on low power machines, it's going to take a while. I don't have an iPhone to do any comprehensive testing but the N value you have is much bigger than is commonly used, and should be expected to run for a long time.
