### ISSUE TITLE
Setting fixed salt with libscrypt_hash

### ISSUE THREAD

**Issue by Slips-PC** [technion/libscrypt#58]
Title is self explanatory. How can I set a fixed salt in the libscrypt_hash function, for i.e getting a specific salt from the system to check password input against a predetermined hash.

**Comment by technion** [comment]
This function is described in the README.
`
int libscrypt_scrypt(const uint8_t *passwd, size_t passwdlen,
        const uint8_t *salt, size_t saltlen, uint64_t N, uint32_t r, 
        uint32_t p, /*@out@*/ uint8_t *buf, size_t buflen);
`
